name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix: 
        node-version: [18.x]
      
    steps:
      - uses: actions/checkout@v2
      - run: npm i -g firebase && npm i -g firebase-tools
      - run: npm i && npm run build && npm ci
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_COMMON_OAUTH_21B7D }}'
          channelId: live
          projectId: common-oauth-21b7d
